//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coachdevEntities : DbContext
    {
        public coachdevEntities()
            : base("name=coachdevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apptransaction> apptransactions { get; set; }
        public virtual DbSet<apptransaction_errorlog> apptransaction_errorlog { get; set; }
        public virtual DbSet<apptransaction_eventlog> apptransaction_eventlog { get; set; }
        public virtual DbSet<briefing> briefings { get; set; }
        public virtual DbSet<briefing_type> briefing_type { get; set; }
        public virtual DbSet<errorlog> errorlogs { get; set; }
        public virtual DbSet<eventlog> eventlogs { get; set; }
        public virtual DbSet<eventtask> eventtasks { get; set; }
        public virtual DbSet<goal> goals { get; set; }
        public virtual DbSet<goal_goal> goal_goal { get; set; }
        public virtual DbSet<goal_location> goal_location { get; set; }
        public virtual DbSet<goal_note> goal_note { get; set; }
        public virtual DbSet<goal_photo> goal_photo { get; set; }
        public virtual DbSet<goal_routine> goal_routine { get; set; }
        public virtual DbSet<goal_tag> goal_tag { get; set; }
        public virtual DbSet<goal_time> goal_time { get; set; }
        public virtual DbSet<goal_todo> goal_todo { get; set; }
        public virtual DbSet<goal_type> goal_type { get; set; }
        public virtual DbSet<inventoryitem> inventoryitems { get; set; }
        public virtual DbSet<inventoryitem_briefing> inventoryitem_briefing { get; set; }
        public virtual DbSet<inventoryitem_goal> inventoryitem_goal { get; set; }
        public virtual DbSet<inventoryitem_logitem> inventoryitem_logitem { get; set; }
        public virtual DbSet<inventoryitem_routine> inventoryitem_routine { get; set; }
        public virtual DbSet<inventoryitem_todo> inventoryitem_todo { get; set; }
        public virtual DbSet<keyvalue> keyvalues { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<logentry> logentries { get; set; }
        public virtual DbSet<logentry_itemfield> logentry_itemfield { get; set; }
        public virtual DbSet<logfield> logfields { get; set; }
        public virtual DbSet<logitem> logitems { get; set; }
        public virtual DbSet<logitem_field> logitem_field { get; set; }
        public virtual DbSet<logitemfield_keyvalue> logitemfield_keyvalue { get; set; }
        public virtual DbSet<note> notes { get; set; }
        public virtual DbSet<photo> photos { get; set; }
        public virtual DbSet<repeat> repeats { get; set; }
        public virtual DbSet<repeat_time> repeat_time { get; set; }
        public virtual DbSet<routine> routines { get; set; }
        public virtual DbSet<routine_eventtask> routine_eventtask { get; set; }
        public virtual DbSet<routine_location> routine_location { get; set; }
        public virtual DbSet<routine_note> routine_note { get; set; }
        public virtual DbSet<routine_photo> routine_photo { get; set; }
        public virtual DbSet<routine_repeat> routine_repeat { get; set; }
        public virtual DbSet<routine_routine> routine_routine { get; set; }
        public virtual DbSet<routine_tag> routine_tag { get; set; }
        public virtual DbSet<routine_todo> routine_todo { get; set; }
        public virtual DbSet<routine_type> routine_type { get; set; }
        public virtual DbSet<sleeprequirement> sleeprequirements { get; set; }
        public virtual DbSet<sleepsession> sleepsessions { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<time> times { get; set; }
        public virtual DbSet<todo> todoes { get; set; }
        public virtual DbSet<todo_eventtask> todo_eventtask { get; set; }
        public virtual DbSet<todo_location> todo_location { get; set; }
        public virtual DbSet<todo_note> todo_note { get; set; }
        public virtual DbSet<todo_photo> todo_photo { get; set; }
        public virtual DbSet<todo_repeat> todo_repeat { get; set; }
        public virtual DbSet<todo_tag> todo_tag { get; set; }
        public virtual DbSet<todo_time> todo_time { get; set; }
        public virtual DbSet<todo_todo> todo_todo { get; set; }
        public virtual DbSet<todo_type> todo_type { get; set; }
        public virtual DbSet<type> types { get; set; }
        public virtual DbSet<type_type> type_type { get; set; }
        public virtual DbSet<goal_view> goal_view { get; set; }
        public virtual DbSet<logitemfield_view> logitemfield_view { get; set; }
        public virtual DbSet<routine_view> routine_view { get; set; }
        public virtual DbSet<todo_view> todo_view { get; set; }
    }
}
