//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public errorlog()
        {
            this.apptransaction_errorlog = new HashSet<apptransaction_errorlog>();
        }
    
        public int id { get; set; }
        public System.DateTime datetime { get; set; }
        public string logMessage { get; set; }
        public string errorSource { get; set; }
        public string errorMessage { get; set; }
        public string stackTrace { get; set; }
        public string endpoint { get; set; }
        public string username { get; set; }
        public string machineName { get; set; }
        public string eventLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apptransaction_errorlog> apptransaction_errorlog { get; set; }
    }
}
