//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eventlog()
        {
            this.apptransaction_eventlog = new HashSet<apptransaction_eventlog>();
        }
    
        public int id { get; set; }
        public System.DateTime datetime { get; set; }
        public string logMessage { get; set; }
        public int dataKey { get; set; }
        public string dataTable { get; set; }
        public string dataValue { get; set; }
        public string crud { get; set; }
        public string endpoint { get; set; }
        public string username { get; set; }
        public string machineName { get; set; }
        public string eventLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<apptransaction_eventlog> apptransaction_eventlog { get; set; }
    }
}
