//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class goal_view
    {
        public int id { get; set; }
        public string title { get; set; }
        public string parents { get; set; }
        public string children { get; set; }
        public string text { get; set; }
        public string description { get; set; }
        public Nullable<sbyte> isVisible { get; set; }
        public sbyte isActive { get; set; }
        public string types { get; set; }
        public string inventoryItems { get; set; }
        public string todos { get; set; }
        public string routines { get; set; }
        public string typeIDs { get; set; }
        public string parentIDs { get; set; }
        public string childIDs { get; set; }
        public string inventoryItemIDs { get; set; }
        public string todoIDs { get; set; }
        public string routineIDs { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    }
}
