//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryitem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventoryitem()
        {
            this.inventoryitem_logitem = new HashSet<inventoryitem_logitem>();
            this.inventoryitem_briefing = new HashSet<inventoryitem_briefing>();
            this.inventoryitem_goal = new HashSet<inventoryitem_goal>();
            this.inventoryitem_routine = new HashSet<inventoryitem_routine>();
            this.inventoryitem_todo = new HashSet<inventoryitem_todo>();
        }
    
        public int id { get; set; }
        public string text { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<int> logPosition { get; set; }
        public string description { get; set; }
        public string json { get; set; }
        public string misc { get; set; }
        public sbyte isActive { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
        public Nullable<System.Guid> guid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventoryitem_logitem> inventoryitem_logitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventoryitem_briefing> inventoryitem_briefing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventoryitem_goal> inventoryitem_goal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventoryitem_routine> inventoryitem_routine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventoryitem_todo> inventoryitem_todo { get; set; }
    }
}
