//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class logitem_field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public logitem_field()
        {
            this.logentry_itemfield = new HashSet<logentry_itemfield>();
            this.logitemfield_keyvalue = new HashSet<logitemfield_keyvalue>();
        }
    
        public int id { get; set; }
        public int idLogItem { get; set; }
        public int idLogField { get; set; }
        public string json { get; set; }
        public Nullable<int> position { get; set; }
        public sbyte isVisible { get; set; }
        public sbyte isActive { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logentry_itemfield> logentry_itemfield { get; set; }
        public virtual logfield logfield { get; set; }
        public virtual logitem logitem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logitemfield_keyvalue> logitemfield_keyvalue { get; set; }
    }
}
