//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class repeat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public repeat()
        {
            this.repeat_time = new HashSet<repeat_time>();
            this.todo_repeat = new HashSet<todo_repeat>();
            this.routine_repeat = new HashSet<routine_repeat>();
        }
    
        public int id { get; set; }
        public int idTimeframe { get; set; }
        public int idMoment { get; set; }
        public Nullable<int> idPointInTime { get; set; }
        public int interval { get; set; }
        public int frequency { get; set; }
        public Nullable<int> pointInTimeIndex { get; set; }
        public string description { get; set; }
        public string json { get; set; }
        public string misc { get; set; }
        public sbyte isActive { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repeat_time> repeat_time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<todo_repeat> todo_repeat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<routine_repeat> routine_repeat { get; set; }
        public virtual type type { get; set; }
        public virtual type type1 { get; set; }
        public virtual type type2 { get; set; }
    }
}
