//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class time
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public time()
        {
            this.goal_time = new HashSet<goal_time>();
            this.repeat_time = new HashSet<repeat_time>();
            this.todo_time = new HashSet<todo_time>();
        }
    
        public int id { get; set; }
        public System.DateTime datetime { get; set; }
        public int idType { get; set; }
        public int idEndpoint { get; set; }
        public int idMoment { get; set; }
        public string description { get; set; }
        public string json { get; set; }
        public string misc { get; set; }
        public sbyte isActive { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goal_time> goal_time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<repeat_time> repeat_time { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<todo_time> todo_time { get; set; }
        public virtual type type { get; set; }
        public virtual type endpoint { get; set; }
        public virtual type moment { get; set; }
    }
}
