//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Service._Date._CoachModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coachEntities : DbContext
    {
        public coachEntities()
            : base("name=coachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<deadline> deadlines { get; set; }
        public DbSet<@event> events { get; set; }
        public DbSet<goal> goals { get; set; }
        public DbSet<goal_goal> goal_goal { get; set; }
        public DbSet<goal_note> goal_note { get; set; }
        public DbSet<goal_repeat> goal_repeat { get; set; }
        public DbSet<goal_routine> goal_routine { get; set; }
        public DbSet<goal_tag> goal_tag { get; set; }
        public DbSet<goal_timeframe> goal_timeframe { get; set; }
        public DbSet<goal_todoitem> goal_todoitem { get; set; }
        public DbSet<goal_type> goal_type { get; set; }
        public DbSet<inventoryitem> inventoryitems { get; set; }
        public DbSet<inventoryitem_goal> inventoryitem_goal { get; set; }
        public DbSet<inventoryitem_routine> inventoryitem_routine { get; set; }
        public DbSet<inventoryitem_todoitem> inventoryitem_todoitem { get; set; }
        public DbSet<inventoryitemspotlight> inventoryitemspotlights { get; set; }
        public DbSet<medium> media { get; set; }
        public DbSet<note> notes { get; set; }
        public DbSet<repeat> repeats { get; set; }
        public DbSet<repeat_dayofmonth> repeat_dayofmonth { get; set; }
        public DbSet<repeat_dayofweek> repeat_dayofweek { get; set; }
        public DbSet<repeat_month> repeat_month { get; set; }
        public DbSet<routine> routines { get; set; }
        public DbSet<routine_note> routine_note { get; set; }
        public DbSet<routine_repeat> routine_repeat { get; set; }
        public DbSet<routine_tag> routine_tag { get; set; }
        public DbSet<routine_todoitem> routine_todoitem { get; set; }
        public DbSet<routine_type> routine_type { get; set; }
        public DbSet<tag> tags { get; set; }
        public DbSet<task> tasks { get; set; }
        public DbSet<task_event> task_event { get; set; }
        public DbSet<task_routine> task_routine { get; set; }
        public DbSet<task_todoitem> task_todoitem { get; set; }
        public DbSet<time> times { get; set; }
        public DbSet<timeframe> timeframes { get; set; }
        public DbSet<todoitem> todoitems { get; set; }
        public DbSet<todoitem_medium> todoitem_medium { get; set; }
        public DbSet<todoitem_note> todoitem_note { get; set; }
        public DbSet<todoitem_repeat> todoitem_repeat { get; set; }
        public DbSet<todoitem_tag> todoitem_tag { get; set; }
        public DbSet<todoitem_timeframe> todoitem_timeframe { get; set; }
        public DbSet<todoitem_todoitem> todoitem_todoitem { get; set; }
        public DbSet<todoitem_type> todoitem_type { get; set; }
        public DbSet<type> types { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<event_view> event_view { get; set; }
        public DbSet<goal_view> goal_view { get; set; }
        public DbSet<inventoryitem_view> inventoryitem_view { get; set; }
        public DbSet<repeat_view> repeat_view { get; set; }
        public DbSet<routine_view> routine_view { get; set; }
        public DbSet<task_view> task_view { get; set; }
        public DbSet<todoitem_view> todoitem_view { get; set; }
        public DbSet<event_type> event_type { get; set; }
    }
}
