//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Service._Date._CoachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class todoitem
    {
        public todoitem()
        {
            this.goal_todoitem = new HashSet<goal_todoitem>();
            this.inventoryitem_todoitem = new HashSet<inventoryitem_todoitem>();
            this.routine_todoitem = new HashSet<routine_todoitem>();
            this.task_todoitem = new HashSet<task_todoitem>();
            this.todoitem_medium = new HashSet<todoitem_medium>();
            this.todoitem_note = new HashSet<todoitem_note>();
            this.todoitem_repeat = new HashSet<todoitem_repeat>();
            this.todoitem_tag = new HashSet<todoitem_tag>();
            this.todoitem_timeframe = new HashSet<todoitem_timeframe>();
            this.todoitem_todoitem = new HashSet<todoitem_todoitem>();
            this.todoitem_todoitem1 = new HashSet<todoitem_todoitem>();
            this.todoitem_type = new HashSet<todoitem_type>();
        }
    
        public int idToDoItem { get; set; }
        public Nullable<bool> isGroup { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public string description { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<int> position { get; set; }
        public Nullable<decimal> percentComplete { get; set; }
        public Nullable<int> estimatedTime { get; set; }
        public Nullable<int> idDeadline { get; set; }
        public Nullable<int> idTime { get; set; }
        public Nullable<bool> isReviewable { get; set; }
        public Nullable<bool> isComplete { get; set; }
        public Nullable<bool> isVisible { get; set; }
        public bool isActive { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual deadline deadline { get; set; }
        public virtual ICollection<goal_todoitem> goal_todoitem { get; set; }
        public virtual ICollection<inventoryitem_todoitem> inventoryitem_todoitem { get; set; }
        public virtual ICollection<routine_todoitem> routine_todoitem { get; set; }
        public virtual ICollection<task_todoitem> task_todoitem { get; set; }
        public virtual time time { get; set; }
        public virtual ICollection<todoitem_medium> todoitem_medium { get; set; }
        public virtual ICollection<todoitem_note> todoitem_note { get; set; }
        public virtual ICollection<todoitem_repeat> todoitem_repeat { get; set; }
        public virtual ICollection<todoitem_tag> todoitem_tag { get; set; }
        public virtual ICollection<todoitem_timeframe> todoitem_timeframe { get; set; }
        public virtual ICollection<todoitem_todoitem> todoitem_todoitem { get; set; }
        public virtual ICollection<todoitem_todoitem> todoitem_todoitem1 { get; set; }
        public virtual ICollection<todoitem_type> todoitem_type { get; set; }
    }
}
