//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Service._Date._CoachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class type
    {
        public type()
        {
            this.goal_type = new HashSet<goal_type>();
            this.routine_type = new HashSet<routine_type>();
            this.todoitem_type = new HashSet<todoitem_type>();
            this.event_type = new HashSet<event_type>();
        }
    
        public int idType { get; set; }
        public string type1 { get; set; }
        public string description { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual ICollection<goal_type> goal_type { get; set; }
        public virtual ICollection<routine_type> routine_type { get; set; }
        public virtual ICollection<todoitem_type> todoitem_type { get; set; }
        public virtual ICollection<event_type> event_type { get; set; }
    }
}
