//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.ServiceOG._Data._CoachModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class coachogEntities : DbContext
    {
        public coachogEntities()
            : base("name=coachogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<deadline> deadlines { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<event_type> event_type { get; set; }
        public virtual DbSet<fooditem> fooditems { get; set; }
        public virtual DbSet<fooditem_nutrient> fooditem_nutrient { get; set; }
        public virtual DbSet<goal> goals { get; set; }
        public virtual DbSet<goal_goal> goal_goal { get; set; }
        public virtual DbSet<goal_note> goal_note { get; set; }
        public virtual DbSet<goal_repeat> goal_repeat { get; set; }
        public virtual DbSet<goal_routine> goal_routine { get; set; }
        public virtual DbSet<goal_tag> goal_tag { get; set; }
        public virtual DbSet<goal_timeframe> goal_timeframe { get; set; }
        public virtual DbSet<goal_todoitem> goal_todoitem { get; set; }
        public virtual DbSet<goal_type> goal_type { get; set; }
        public virtual DbSet<inventoryitem> inventoryitems { get; set; }
        public virtual DbSet<inventoryitem_goal> inventoryitem_goal { get; set; }
        public virtual DbSet<inventoryitem_logitem> inventoryitem_logitem { get; set; }
        public virtual DbSet<inventoryitem_routine> inventoryitem_routine { get; set; }
        public virtual DbSet<inventoryitem_todoitem> inventoryitem_todoitem { get; set; }
        public virtual DbSet<inventoryitemspotlight> inventoryitemspotlights { get; set; }
        public virtual DbSet<keyvalue> keyvalues { get; set; }
        public virtual DbSet<keyvalue_type> keyvalue_type { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<logentry> logentries { get; set; }
        public virtual DbSet<logentry_itemfield> logentry_itemfield { get; set; }
        public virtual DbSet<logentry_logitemfield> logentry_logitemfield { get; set; }
        public virtual DbSet<logfield> logfields { get; set; }
        public virtual DbSet<logitem> logitems { get; set; }
        public virtual DbSet<logitem_field> logitem_field { get; set; }
        public virtual DbSet<logitemfield> logitemfields { get; set; }
        public virtual DbSet<logitemfield_keyvalue> logitemfield_keyvalue { get; set; }
        public virtual DbSet<meal> meals { get; set; }
        public virtual DbSet<meal_fooditem> meal_fooditem { get; set; }
        public virtual DbSet<meal_meal> meal_meal { get; set; }
        public virtual DbSet<meal_type> meal_type { get; set; }
        public virtual DbSet<meal_waterlog> meal_waterlog { get; set; }
        public virtual DbSet<medium> media { get; set; }
        public virtual DbSet<note> notes { get; set; }
        public virtual DbSet<nutrient> nutrients { get; set; }
        public virtual DbSet<photo> photos { get; set; }
        public virtual DbSet<repeat> repeats { get; set; }
        public virtual DbSet<repeat_dayofmonth> repeat_dayofmonth { get; set; }
        public virtual DbSet<repeat_dayofweek> repeat_dayofweek { get; set; }
        public virtual DbSet<repeat_month> repeat_month { get; set; }
        public virtual DbSet<routine> routines { get; set; }
        public virtual DbSet<routine_note> routine_note { get; set; }
        public virtual DbSet<routine_repeat> routine_repeat { get; set; }
        public virtual DbSet<routine_tag> routine_tag { get; set; }
        public virtual DbSet<routine_todoitem> routine_todoitem { get; set; }
        public virtual DbSet<routine_type> routine_type { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<task_event> task_event { get; set; }
        public virtual DbSet<task_meal> task_meal { get; set; }
        public virtual DbSet<task_routine> task_routine { get; set; }
        public virtual DbSet<task_todoitem> task_todoitem { get; set; }
        public virtual DbSet<task_type> task_type { get; set; }
        public virtual DbSet<time> times { get; set; }
        public virtual DbSet<timeframe> timeframes { get; set; }
        public virtual DbSet<todoitem> todoitems { get; set; }
        public virtual DbSet<todoitem_medium> todoitem_medium { get; set; }
        public virtual DbSet<todoitem_note> todoitem_note { get; set; }
        public virtual DbSet<todoitem_repeat> todoitem_repeat { get; set; }
        public virtual DbSet<todoitem_tag> todoitem_tag { get; set; }
        public virtual DbSet<todoitem_timeframe> todoitem_timeframe { get; set; }
        public virtual DbSet<todoitem_todoitem> todoitem_todoitem { get; set; }
        public virtual DbSet<todoitem_type> todoitem_type { get; set; }
        public virtual DbSet<type> types { get; set; }
        public virtual DbSet<type_type> type_type { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<waterlog> waterlogs { get; set; }
        public virtual DbSet<goal_view> goal_view { get; set; }
        public virtual DbSet<inventory_logitemfield_view> inventory_logitemfield_view { get; set; }
        public virtual DbSet<inventoryitem_view> inventoryitem_view { get; set; }
        public virtual DbSet<logitemfield_view> logitemfield_view { get; set; }
        public virtual DbSet<repeat_view> repeat_view { get; set; }
        public virtual DbSet<routine_view> routine_view { get; set; }
        public virtual DbSet<task_mealfooditemnutrient_view> task_mealfooditemnutrient_view { get; set; }
        public virtual DbSet<task_view> task_view { get; set; }
        public virtual DbSet<todoitem_view> todoitem_view { get; set; }
        public virtual DbSet<waterlog_mealtask_view> waterlog_mealtask_view { get; set; }
        public virtual DbSet<event_view> event_view { get; set; }
    }
}
