//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.ServiceOG._Data._CoachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_logitemfield_view
    {
        public Nullable<int> idInventoryItem { get; set; }
        public int idLogItem { get; set; }
        public int idLogItemField { get; set; }
        public int idType_Data { get; set; }
        public int idType_Field { get; set; }
        public string inventoryItem { get; set; }
        public Nullable<int> inventoryItem_Position { get; set; }
        public string logItem { get; set; }
        public Nullable<int> position_LogItem { get; set; }
        public bool isActive_LogItem { get; set; }
        public string field { get; set; }
        public string dataType { get; set; }
        public string fieldType { get; set; }
        public Nullable<int> position_Field { get; set; }
        public bool isActive_Field { get; set; }
    }
}
