//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.ServiceOG._Data._CoachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class logentry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public logentry()
        {
            this.logentry_logitemfield = new HashSet<logentry_logitemfield>();
            this.logentry_itemfield = new HashSet<logentry_itemfield>();
        }
    
        public int idLogEntry { get; set; }
        public int idLogItem { get; set; }
        public Nullable<int> idLocation { get; set; }
        public string reason { get; set; }
        public System.DateTime dateTime { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logentry_logitemfield> logentry_logitemfield { get; set; }
        public virtual location location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logentry_itemfield> logentry_itemfield { get; set; }
        public virtual logitem logitem { get; set; }
    }
}
