//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.ServiceOG._Data._CoachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class meal_fooditem
    {
        public int idMeal_FoodItem { get; set; }
        public int idMeal { get; set; }
        public int idFoodItem { get; set; }
        public Nullable<double> quantity { get; set; }
        public string unit { get; set; }
        public bool wasConsumed { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual meal meal { get; set; }
        public virtual fooditem fooditem { get; set; }
    }
}
