//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.ServiceOG._Data._CoachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class nutrient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nutrient()
        {
            this.fooditem_nutrient = new HashSet<fooditem_nutrient>();
        }
    
        public int idNutrient { get; set; }
        public string name { get; set; }
        public string unit { get; set; }
        public string usdaTag { get; set; }
        public string nutritionixName { get; set; }
        public string nutritionixFieldName { get; set; }
        public string nutritionixUnit { get; set; }
        public Nullable<int> nutritionixAttrID { get; set; }
        public string ntrCode { get; set; }
        public string myFitnessPalName { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updateAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fooditem_nutrient> fooditem_nutrient { get; set; }
    }
}
