//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.ServiceOG._Data._CoachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class repeat_view
    {
        public int idRepeat { get; set; }
        public int idTimeframe { get; set; }
        public string timeframe { get; set; }
        public int interval { get; set; }
        public int frequency { get; set; }
        public string repeat_MonthIDs { get; set; }
        public string repeat_DayOfMonthIDs { get; set; }
        public string repeat_DayOfWeekIDs { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    }
}
