//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.ServiceOG._Data._CoachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_type
    {
        public int idTask_Type { get; set; }
        public int idTask { get; set; }
        public int idType { get; set; }
    
        public virtual task task { get; set; }
        public virtual type type { get; set; }
    }
}
