//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Service._Date._CoachModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_veiw
    {
        public int idTask { get; set; }
        public string label { get; set; }
        public string text { get; set; }
        public string type { get; set; }
        public string timeframe { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public Nullable<System.DateTime> dateTimeCompleted { get; set; }
        public Nullable<int> idTime { get; set; }
        public Nullable<bool> isComplete { get; set; }
        public Nullable<bool> isVisible { get; set; }
        public bool isActive_Task { get; set; }
        public Nullable<bool> isActive_TodoItem { get; set; }
        public Nullable<int> idTodoItem { get; set; }
        public Nullable<int> idRoutine { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    }
}
