//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model.OG
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_type
    {
        public int idEvent_Type { get; set; }
        public int idEvent { get; set; }
        public int idType { get; set; }
    
        public virtual type type { get; set; }
        public virtual @event @event { get; set; }
    }
}
