//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model.OG
{
    using System;
    using System.Collections.Generic;
    
    public partial class fooditem_nutrient
    {
        public int idFoodItem_Nutrient { get; set; }
        public int idFoodItem { get; set; }
        public int idNutrient { get; set; }
        public Nullable<double> nutrientQuantity { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual fooditem fooditem { get; set; }
        public virtual nutrient nutrient { get; set; }
    }
}
