//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model.OG
{
    using System;
    using System.Collections.Generic;
    
    public partial class logentry_logitemfield
    {
        public int idLogEntry_LogItemField { get; set; }
        public int idLogEntry { get; set; }
        public int idLogItemField { get; set; }
        public string value { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual logentry logentry { get; set; }
        public virtual logitemfield logitemfield { get; set; }
    }
}
