//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model.OG
{
    using System;
    using System.Collections.Generic;
    
    public partial class meal_waterlog
    {
        public int idMeal_WaterLog { get; set; }
        public int idMeal { get; set; }
        public int idWaterLog { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        public virtual meal meal { get; set; }
        public virtual waterlog waterlog { get; set; }
    }
}
