//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model.OG
{
    using System;
    using System.Collections.Generic;
    
    public partial class time
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public time()
        {
            this.routines = new HashSet<routine>();
            this.tasks = new HashSet<task>();
            this.todoitems = new HashSet<todoitem>();
        }
    
        public int idTime { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public string startDayOfWeek { get; set; }
        public Nullable<int> startDayOfMonth { get; set; }
        public string startPosition { get; set; }
        public Nullable<System.DateTime> startWeek { get; set; }
        public Nullable<System.DateTime> startMonth { get; set; }
        public Nullable<System.DateTime> startYear { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string endDayOfWeek { get; set; }
        public Nullable<int> endDayOfMonth { get; set; }
        public string endPosition { get; set; }
        public Nullable<System.DateTime> endWeek { get; set; }
        public Nullable<System.DateTime> endMonth { get; set; }
        public Nullable<System.DateTime> endYear { get; set; }
        public Nullable<System.TimeSpan> recommendedStartTime { get; set; }
        public Nullable<System.DateTime> recommendedStartDate { get; set; }
        public string recommendedStartDayOfWeek { get; set; }
        public Nullable<int> recommendedStartDayOfMonth { get; set; }
        public string recommendedStartPosition { get; set; }
        public Nullable<System.DateTime> recommendedStartWeek { get; set; }
        public Nullable<System.DateTime> recommendedStartMonth { get; set; }
        public Nullable<System.DateTime> recommendedStartYear { get; set; }
        public Nullable<System.TimeSpan> recommendedEndTime { get; set; }
        public Nullable<System.DateTime> recommendedEndDate { get; set; }
        public string recommendedEndDayOfWeek { get; set; }
        public Nullable<int> recommendedEndDayOfMonth { get; set; }
        public string recommendedEndPosition { get; set; }
        public Nullable<System.DateTime> recommenedEndWeek { get; set; }
        public Nullable<System.DateTime> recommendedEndMonth { get; set; }
        public Nullable<System.DateTime> recommendedEndYear { get; set; }
        public Nullable<System.TimeSpan> dueTime { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public string dueDayOfWeek { get; set; }
        public Nullable<int> dueDayOfMonth { get; set; }
        public string duePosition { get; set; }
        public Nullable<System.DateTime> dueWeek { get; set; }
        public Nullable<System.DateTime> dueMonth { get; set; }
        public Nullable<System.DateTime> dueYear { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<routine> routines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task> tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<todoitem> todoitems { get; set; }
    }
}
