//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model.OG
{
    using System;
    using System.Collections.Generic;
    
    public partial class todoitem_view
    {
        public int idTodoItem { get; set; }
        public Nullable<bool> isGroup { get; set; }
        public string parents { get; set; }
        public string children { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<decimal> percentComplete { get; set; }
        public Nullable<int> estimatedTime { get; set; }
        public Nullable<int> idDeadline { get; set; }
        public string types { get; set; }
        public string timeframes { get; set; }
        public string inventoryItems { get; set; }
        public string goals { get; set; }
        public string routines { get; set; }
        public Nullable<int> idTime { get; set; }
        public Nullable<bool> isReviewable { get; set; }
        public Nullable<bool> isComplete { get; set; }
        public Nullable<bool> isVisible { get; set; }
        public bool isActive { get; set; }
        public string typeIDs { get; set; }
        public string timeframeIDs { get; set; }
        public string repeatIDs { get; set; }
        public string parentIDs { get; set; }
        public string childIDs { get; set; }
        public string inventoryItemIDs { get; set; }
        public string goalIDs { get; set; }
        public string routineIDs { get; set; }
        public string taskIDs { get; set; }
        public string eventIDs { get; set; }
        public System.DateTime createdAt { get; set; }
        public System.DateTime updatedAt { get; set; }
    }
}
