//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Data.Model.OG
{
    using System;
    using System.Collections.Generic;
    
    public partial class waterlog_mealtask_view
    {
        public int idWaterLog { get; set; }
        public Nullable<int> idMeal { get; set; }
        public Nullable<int> idMeal_WaterLog { get; set; }
        public Nullable<int> idTask { get; set; }
        public string mealName { get; set; }
        public int amount { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
    }
}
