//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Service._Data._JSONModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jsonEntities : DbContext
    {
        public jsonEntities()
            : base("name=jsonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Goal> Goals { get; set; }
        public DbSet<InventoryItem> InventoryItems { get; set; }
        public DbSet<Routine> Routines { get; set; }
        public DbSet<TodoItem> TodoItems { get; set; }
    }
}
