//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Service._Data._JSONModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routine
    {
        public int idRoutine { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string idGoals { get; set; }
        public string idParents { get; set; }
        public string idChildren { get; set; }
        public string idTodoItems { get; set; }
        public Nullable<bool> Active { get; set; }
        public string idInventoryItems { get; set; }
    }
}
