//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coach.Service._Data._JSONModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoItem
    {
        public int idTodoItem { get; set; }
        public string Label { get; set; }
        public string Type { get; set; }
        public string Repetition { get; set; }
        public string Timeframe { get; set; }
        public string Deadline { get; set; }
        public string Medium { get; set; }
        public string idInventoryItems { get; set; }
        public string idParents { get; set; }
        public string idChildren { get; set; }
        public string idGoals { get; set; }
        public string idRoutines { get; set; }
        public Nullable<bool> IsGroup { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
